/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_codingapi_jni_HelloWord */

#ifndef _Included_com_codingapi_jni_HelloWord
#define _Included_com_codingapi_jni_HelloWord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_codingapi_jni_HelloWord
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_codingapi_jni_HelloWord_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
